name: Release

on:
    push:
        branches: ["main"]
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Minify JSON
              uses: StefanEnsmann/Minify-JSON-Action@1.1.0
              with:
                  input_file: source.json
                  output_file: min_source.json

            - name: Commit and push changes
              uses: stefanzweifel/git-auto-commit-action@v4
              with:
                  commit_message: "Add minified JSON file"
                  file_pattern: min_source.json
