name: Release

on:
    push:
        branches: ["main"]
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Minify JSON
              uses: StefanEnsmann/Minify-JSON-Action@1.1.0
              with:
                  input_file: source.json
                  output_file: min_source.json
